"""second migration

Revision ID: c678aa6e6807
Revises: e3eff707a713
Create Date: 2019-09-19 10:02:14.256995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c678aa6e6807'
down_revision = 'e3eff707a713'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('user', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
