"""second migration

Revision ID: e3eff707a713
Revises: 1aff9fe1b507
Create Date: 2019-09-19 10:00:35.451450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3eff707a713'
down_revision = '1aff9fe1b507'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('user', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'user')
    # ### end Alembic commands ###
